<a href="https://colab.research.google.com/github/junghyeonsu/Academy-react-native/blob/master/10%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow.compat.v1 as tf
tf.disable_resource_variables()
tf.set_random_seed(777)

In [27]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [29]:
xy = np.loadtxt('/content/gdrive/My Drive/Colab Notebooks/data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = xy[:,0:-1] # 0~2열을 가져와라
y_data = xy[:, [-1]] # 마지막 열을 가져와라

print(x_data)
print(y_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [0]:
X = tf.placeholder(tf.float32, shape=[None, 3]) #개수는 몇개가져올지 모르겠고~ (None), 열은 3개야!
Y = tf.placeholder(tf.float32, shape=[None, 1]) #개수는 몇개가져올지 모르겠고~ (None), 열은 하나야! 

W = tf.Variable(tf.random_normal([3,1]), name='weight') # W는 3,1 행렬을 가진다! 왜? 3개의 '기준척도' 그리고 하나의 데이터!
b = tf.Variable(tf.random_normal([1]), name ='bias')

In [0]:
hypothesis = tf.matmul(X,W) + b # matmul 은 매트릭스 곱하기를 뜻한다.

cost = tf.reduce_mean(tf.square(hypothesis - Y)) #코스트 함수는 (가설 - 실제값)^2 의 평균!

옵티마이저는 텐서플로우의 함수를 이용해서 경사하강법을 쓴다!

train은 cost를 최소화하는쪽으로 줄어들게된다!

In [0]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [46]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ = sess.run(
      [cost,hypothesis,train],
      feed_dict={X:x_data, Y:y_data}
  )

  if step % 400 == 0:
    print(
        "Step : ", step,
        "\nCost : ", cost_val,
        "\nPrediction : ",hy_val
          )
    print("\n")

Step :  0 
Cost :  12285.612 
Prediction :  [[52.488823]
 [55.98236 ]
 [58.799793]
 [65.84191 ]
 [39.16055 ]
 [30.272982]
 [53.536842]
 [45.972366]
 [52.58834 ]
 [51.687588]
 [47.600456]
 [44.313225]
 [58.921963]
 [45.836678]
 [52.875298]
 [59.121807]
 [39.249   ]
 [67.2888  ]
 [56.978317]
 [51.949444]
 [61.347282]
 [54.56272 ]
 [58.570843]
 [48.64899 ]
 [58.42142 ]]


Step :  400 
Cost :  15.472499 
Prediction :  [[156.18835 ]
 [181.526   ]
 [182.03252 ]
 [200.05757 ]
 [135.1283  ]
 [101.140594]
 [153.75592 ]
 [119.897995]
 [170.13498 ]
 [160.65804 ]
 [144.4206  ]
 [140.18196 ]
 [186.24927 ]
 [151.7365  ]
 [153.69102 ]
 [186.44061 ]
 [140.3792  ]
 [187.35503 ]
 [178.22623 ]
 [160.34023 ]
 [178.99826 ]
 [172.28674 ]
 [170.66338 ]
 [153.22156 ]
 [188.38843 ]]


Step :  800 
Cost :  13.617057 
Prediction :  [[155.8016 ]
 [181.8597 ]
 [181.94997]
 [199.96672]
 [135.5819 ]
 [101.56641]
 [153.46194]
 [119.34067]
 [170.63065]
 [161.18607]
 [144.3765 ]
 [140.49033]
 [186.17987]
 [151.73479]
 

In [51]:
print("너의 점수는", sess.run(hypothesis, feed_dict={X:[[100,70,101]]}), "일거야")

print("너의 점수는", sess.run(hypothesis, feed_dict={X: [[1,1,1], [4,4,4]]}), "일거야")

너의 점수는 [[176.8839]] 일거야
너의 점수는 [[0.71984386]
 [6.791006  ]] 일거야
